# Site Settings
baseurl: 		""
title: 			Javascript for Designers
name: 			Javascript {for} Designers
description: 	Introducing a practical Javascript course with designers in mind! Learn everyday JS fundamentals that will let you bring your UI/UX vision to life.
url: 			"http://www.javascriptfordesigners.io"

# This will require each of these plugins automatically.
plugins: ["jekyll-paginate", "jekyll-time-to-read"]

paginate: 		3
paginate_path: 	"blog/page:num"

twitter: 		johnludena
email: 			hello@javascriptfordesigners.io

disqus: 		your_disqus_shortname
analytics: 		UA-9053515-18

copyright: 		Copyright 2017 Javascript for Designers.	

# Build Settings
permalinks: 	pretty